version: '3.8'

volumes:
  secret_information_log:
  pandomi_log:
  pandomi_random_log:
services:
  secret_information:
    image: "panda1024/secret_information:v0.2"
    container_name: secret_information
    restart: always
    ports:
      - '8681:8088'
    expose:
      - 8681
    volumes:
      - 'secret_information_log:/var/log'


  pandomi:
    image: "panda1024/pandomi:v0.2"
    container_name: pandomi
    restart: always
    ports:
      - '28459:8089'
    expose:
      - 28459
    volumes:
      - 'pandomi_log:/var/log'

  pandomi-random:
    container_name: pandomi-random
    expose:
      - 28458
    ports:
      - "28458:8080"
    volumes:
      - "pandomi_random_log:/var/log"
    image: "panda1024/pandomi-random:v0.1"
    restart: always